최종 빌드 경로 세팅 및 카메라 조향 추가가

diff --git a/.github/workflows/buildGL.yml b/.github/workflows/buildGL.yml
--- a/.github/workflows/buildGL.yml
+++ b/.github/workflows/buildGL.yml
@@ -41,15 +41,15 @@ jobs:
       - name: Check build output
         run: |
           ls -l .
-          ls -l ./Build || echo "Build directory not found"
+          ls -l ./build || echo "Build directory not found"
 
       - name: Add .nojekyll
-        run: echo "" > ./Build/WebGL/.nojekyll
+        run: echo "" > ./build/WebGL/.nojekyll
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./Build/WebGL
+          publish_dir: ./build/WebGL
           publish_branch: gh-pages
           force_orphan: true
